[package]
name = "storj-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "DRPC client frame codec and unary invoke"
repository.workspace = true
homepage.workspace = true
exclude = ["testdata/**"]

[dependencies]
thiserror.workspace = true
tokio.workspace = true
sha2.workspace = true
bs58.workspace = true
p256.workspace = true
rcgen.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
quinn.workspace = true
socket2.workspace = true

snow.workspace = true
zeroize.workspace = true
futures-util.workspace = true
x509-parser.workspace = true

[target.'cfg(any(windows, target_os = "linux", target_os = "android", target_os = "freebsd", target_os = "openbsd", target_os = "netbsd", target_os = "dragonfly", target_os = "macos", target_os = "ios", target_os = "watchos", target_os = "tvos"))'.dependencies]
tokio-tfo.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "io-util", "test-util"] }

[lints]
workspace = true
