//! Argon2id root-key derivation (K14 / R8).
//!
//! Cross-language goldens are generated by `go run -C scripts .`
//! (`storj.io/common/encryption.DeriveRootKey`) and asserted here (hardcoded
//! p=1 / p=8) and in `encryption_golden.rs`.

use storj::EncryptionKey;
use storj::constants::{ARGON2_PARALLELISM_DERIVE, ARGON2_PARALLELISM_REQUEST};
use storj::encryption::derive_root_key;

const PASS: &str = "correct horse battery staple";
const SALT: &[u8] = b"0123456789abcdef"; // 16 bytes; HMAC then Argon2

#[test]
fn derive_matches_empty_path_p1() {
    let via_api = EncryptionKey::derive(PASS, SALT).unwrap();
    let via_raw = derive_root_key(PASS.as_bytes(), SALT, b"", ARGON2_PARALLELISM_DERIVE).unwrap();
    assert_eq!(via_api.as_bytes(), via_raw.as_bytes());
}

#[test]
fn p1_and_p8_diverge() {
    let p1 = derive_root_key(PASS.as_bytes(), SALT, b"", ARGON2_PARALLELISM_DERIVE).unwrap();
    let p8 = derive_root_key(PASS.as_bytes(), SALT, b"", ARGON2_PARALLELISM_REQUEST).unwrap();
    assert_ne!(p1.as_bytes(), p8.as_bytes());
}

#[test]
fn path_is_mixed_into_salt() {
    let empty = derive_root_key(PASS.as_bytes(), SALT, b"", ARGON2_PARALLELISM_DERIVE).unwrap();
    let with_path =
        derive_root_key(PASS.as_bytes(), SALT, b"logs", ARGON2_PARALLELISM_DERIVE).unwrap();
    assert_ne!(empty.as_bytes(), with_path.as_bytes());
}

#[test]
fn known_vector_p1_empty_path() {
    let key = EncryptionKey::derive(PASS, SALT).unwrap();
    let hex = hex::encode(key.as_bytes());
    // HMAC-SHA256 mix + Argon2id t=1,m=65536,p=1,out=32 from
    // storj.io/common encryption.DeriveRootKey.
    assert_eq!(
        hex,
        "b8cf6690304c95e6420e35c6a0c29f30e32505137f8795ea4f4f4d4f886847ec"
    );
}

#[test]
fn known_vector_p8_empty_path() {
    let key = derive_root_key(PASS.as_bytes(), SALT, b"", ARGON2_PARALLELISM_REQUEST).unwrap();
    let got = hex::encode(key.as_bytes());
    // Same mix as p=1; Argon2id t=1,m=65536,p=8,out=32 from
    // storj.io/common encryption.DeriveRootKey (`go run -C scripts .`).
    assert_eq!(
        got,
        "ba6ae767afbf7face4342d1c310fbccf674fd28e3e1c30c964d222f3f8b5e4dd"
    );
    let jsonl = std::fs::read_to_string(storj_test::fixture("derive_root_key.jsonl")).unwrap();
    let row = jsonl
        .lines()
        .find(|l| l.contains("\"parallelism\":8") && l.contains("\"path\":\"\""))
        .expect("jsonl must include empty-path p=8");
    assert!(
        row.contains(&got),
        "jsonl p=8 empty-path must match hardcoded vector: {row}"
    );
}
